This script provides the arguments that we used to instantiate our standardized benchmarking environments. Our standard environments are created with the **Franka Emika Panda** arm using the **Operational Space Controllers**. For reproducible research and fair comparison, please use the same environment setups when comparing to our benchmarking results.

We provide the following nine standardized environments in our current v1.0 release:

- **Block Lifting**
- **Block Stacking**
- **Pick-and-Place Can**: pick-and-place task with only the Can object
- **Nut Assembly Round**: nut assembly task with only the round nut
- **Table Wiping**
- **Door Opening**
- **Two Arm Lifting**: two Panda robots in opposed positions
- **Two Arm Handover**: two Panda robots in opposed positions
- **Two Arm Peg-in-Hole**: two Panda robots in opposed positions

In [27]:
import robosuite as suite
import numpy as np
import torch
seed = 17
np.random.seed(seed)
torch.manual_seed(seed)
# from robosuite import load_controller_config

# load OSC controller to use for all environments
# controller = load_controller_config(default_controller="OSC_POSE")
# controller = {'type': 'BASIC', 'body_parts': {'right': {'type': 'OSC_POSE', 'input_max': 1, 'input_min': -1, 'output_max': [0.05, 0.05, 0.05, 0.5, 0.5, 0.5], 'output_min': [-0.05, -0.05, -0.05, -0.5, -0.5, -0.5], 'kp': 150, 'damping_ratio': 1, 'impedance_mode': 'fixed', 'kp_limits': [0, 300], 'damping_ratio_limits': [0, 10], 'position_limits': None, 'orientation_limits': None, 'uncouple_pos_ori': True, 'input_type': 'delta', 'input_ref_frame': 'base', 'interpolation': None, 'ramp_ratio': 0.2, 'gripper': {'type': 'GRIP'}}, 'left': {'type': 'OSC_POSE', 'input_max': 1, 'input_min': -1, 'output_max': [0.05, 0.05, 0.05, 0.5, 0.5, 0.5], 'output_min': [-0.05, -0.05, -0.05, -0.5, -0.5, -0.5], 'kp': 150, 'damping_ratio': 1, 'impedance_mode': 'fixed', 'kp_limits': [0, 300], 'damping_ratio_limits': [0, 10], 'position_limits': None, 'orientation_limits': None, 'uncouple_pos_ori': True, 'input_type': 'delta', 'input_ref_frame': 'base', 'interpolation': None, 'ramp_ratio': 0.2, 'gripper': {'type': 'GRIP'}}, 'torso': {'type': 'JOINT_POSITION', 'input_max': 1, 'input_min': -1, 'output_max': 0.5, 'output_min': -0.5, 'kd': 200, 'kv': 200, 'kp': 1000, 'velocity_limits': [-1, 1], 'kp_limits': [0, 1000], 'interpolation': None, 'ramp_ratio': 0.2}, 'head': {'type': 'JOINT_POSITION', 'input_max': 1, 'input_min': -1, 'output_max': 0.5, 'output_min': -0.5, 'kd': 200, 'kv': 200, 'kp': 1000, 'velocity_limits': [-1, 1], 'kp_limits': [0, 1000], 'interpolation': None, 'ramp_ratio': 0.2}, 'base': {'type': 'JOINT_VELOCITY', 'interpolation': 'null'}, 'legs': {'type': 'JOINT_POSITION', 'input_max': 1, 'input_min': -1, 'output_max': 0.5, 'output_min': -0.5, 'kd': 200, 'kv': 200, 'kp': 1000, 'velocity_limits': [-1, 1], 'kp_limits': [0, 1000], 'interpolation': None, 'ramp_ratio': 0.2}}}

# these arguments are the same for all envs
config = {
    # "controller_configs": controller,
    "horizon": 500,
    "control_freq": 20,
    "reward_shaping": True,
    "reward_scale": 1.0,
    "use_camera_obs": False,
    "ignore_done": True,
    "hard_reset": False,
}

# this should be used during training to speed up training
# A renderer should be used if you're visualizing rollouts!
config["has_offscreen_renderer"] = False

In [35]:
# Block Lifting

np.random.seed(seed)
torch.manual_seed(seed)
block_lifting_env = suite.make(
    env_name="Lift",
    robots="Panda",
    **config,
)
np.set_printoptions(precision=3, suppress=True, linewidth=200)
o = block_lifting_env.reset()
total = 0
for k, v in o.items():
	print(k, len(v) if not isinstance(v, np.float64) else v,"\t", v)
	total += len(v) if not isinstance(v, np.float64) else 1
print("Total:", total)
print()
print(o['robot0_proprio-state'])

from robosuite.wrappers import GymWrapper

keys = ["object-state"]
for idx in range(len(block_lifting_env.robots)):
	keys.append(f"robot{idx}_proprio-state")

# Wrap environment so it's compatible with Gym API
env = GymWrapper(block_lifting_env, keys=keys)

from pprint import pprint
o_gym = env.reset()
print("Gym Wrapper")
pprint(o_gym)

robot0_joint_pos_cos 7 	 [ 0.999  0.979  0.999 -0.853  1.    -0.975  0.711]
robot0_joint_pos_sin 7 	 [ 0.04   0.206 -0.035 -0.523 -0.009  0.22   0.704]
robot0_joint_vel 7 	 [0. 0. 0. 0. 0. 0. 0.]
robot0_eef_pos 3 	 [-0.096  0.001  1.012]
robot0_eef_quat 4 	 [0.998 0.01  0.06  0.005]
robot0_gripper_qpos 2 	 [ 0.021 -0.021]
robot0_gripper_qvel 2 	 [0. 0.]
cube_pos 3 	 [-0.021 -0.027  0.83 ]
cube_quat 4 	 [ 0.     0.     0.774 -0.633]
gripper_to_cube_pos 3 	 [-0.075  0.028  0.182]
robot0_proprio-state 32 	 [ 0.999  0.979  0.999 -0.853  1.    -0.975  0.711  0.04   0.206 -0.035 -0.523 -0.009  0.22   0.704  0.     0.     0.     0.     0.     0.     0.    -0.096  0.001  1.012  0.998  0.01   0.06   0.005
  0.021 -0.021  0.     0.   ]
object-state 10 	 [-0.021 -0.027  0.83   0.     0.     0.774 -0.633 -0.075  0.028  0.182]
Total: 84

[ 0.999  0.979  0.999 -0.853  1.    -0.975  0.711  0.04   0.206 -0.035 -0.523 -0.009  0.22   0.704  0.     0.     0.     0.     0.     0.     0.    -0.096  0.001  

In [36]:
o["object-state"]

array([-0.021, -0.027,  0.83 ,  0.   ,  0.   ,  0.774, -0.633, -0.075,  0.028,  0.182])

In [32]:
o_new = np.array([-0.193, -0.325,  1.1  , -0.123, -0.238,  1.075, -0.098, -0.316,  0.083, -0.028, -0.229,  0.058,  0.   ,  0.   ,  1.   ,  0.981,  1.   , -0.864,  1.   , -0.985,  0.694,  0.003,  0.192, -0.02 ,
       -0.503,  0.005,  0.174,  0.72 ,  0.   ,  0.   ,  0.   , -0.095, -0.009,  1.017,  0.997, -0.02 ,  0.08 ,  0.001,  0.719,  0.691,  0.055,  0.057,  0.021, -0.021,  0.   ,  0.   ])

In [33]:
o_new-o_gym

array([ 0.   ,  0.   ,  0.   ,  0.   ,  0.   , -0.   , -0.   ,  0.   , -0.   , -0.   ,  0.   , -0.   ,  0.   ,  0.   ,  0.   , -0.   ,  0.   ,  0.   ,  0.   , -0.   ,  0.   ,  0.   , -0.   ,  0.   ,
        0.   ,  0.   ,  0.   , -0.   ,  0.   ,  0.   ,  0.   , -0.095, -0.009,  1.017,  0.997,  0.075,  0.089, -1.016, -0.278,  0.711, -0.025,  0.056,  0.   , -0.   ,  0.   ,  0.   ])

In [12]:
block_lifting_env.object_body_ids


{'door': 25, 'frame': 24, 'latch': 26}

In [17]:
robot0_joint_pos
robot0_eef_quat_site

NameError: name 'robot0_joint_pos' is not defined

In [ ]:
robot0_joint_pos_cos 7
robot0_joint_pos_sin 7
robot0_joint_vel 7
robot0_eef_pos 3
robot0_eef_quat 4
robot0_gripper_qpos 2
robot0_gripper_qvel 2
door_pos 3
handle_pos 3
door_to_eef_pos 3
handle_to_eef_pos 3
hinge_qpos 0.0
handle_qpos 0.0
robot0_proprio-state 32
object-state 14

[robosuite WARNING] The config has defined for the controller "left", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for left from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "torso", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for torso from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "head", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for head from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "base", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for base from self.part_controller_config. (robot.py:151)
[robosuite WARNING] Th

In [6]:
o_gym = env.reset()[0]
o_gym.shape

[robosuite WARNING] The config has defined for the controller "left", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for left from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "torso", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for torso from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "head", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for head from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "base", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for base from self.part_controller_config. (robot.py:151)
[robosuite WARNING] Th

(57,)

In [ ]:
o_gym

In [ ]:

o_gym[:21]

array([-0.205, -0.339,  1.1  , -0.146, -0.244,  1.075,  0.   , -0.097, -0.336,  0.089, -0.038, -0.241,  0.064,  0.   ,  0.002,  0.187, -0.009, -2.629, -0.015,  2.931,  0.791])

In [29]:
a = numpy.array([-0.20773808, -0.345851  ,  1.1       , -0.15032774, -0.24991325,
        1.075     , -0.10944897, -0.33390935,  0.0807272 , -0.05203863,
       -0.2379716 ,  0.0557272 ,  0.        ,  0.        ,  0.99990556,
        0.98394283,  0.99990989, -0.86615202,  0.99975033, -0.98098723,
        0.68324837, -0.01374302,  0.17848393, -0.01342452, -0.49978063,
       -0.02234435,  0.1940723 ,  0.73018605,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
       -0.09828911, -0.01194165,  1.0192728 ,  0.9970546 , -0.0188861 ,
        0.07422784,  0.00395724,  0.020833  , -0.020833  ,  0.        ,
        0.        ])
a.shape

(46,)

In [ ]:
o
total = 0
for k, v in o.items():
	print(k, len(v))
	total += len(v)
print("Total:", total)

robot0_joint_pos 7
robot0_joint_pos_cos 7
robot0_joint_pos_sin 7
robot0_joint_vel 7
robot0_eef_pos 3
robot0_eef_quat 4
robot0_eef_quat_site 4
robot0_gripper_qpos 2
robot0_gripper_qvel 2
cube_pos 3
cube_quat 4
gripper_to_cube_pos 3
robot0_proprio-state 43
object-state 10
Total: 106


In [4]:
# Block Lifting
block_lifting_env = suite.make(
    env_name="Lift",
    robots="Panda",
    **config,
)

# Block Stacking
block_stacking_env = suite.make(
    env_name="Stack",
    robots="Panda",
    **config,
)

# Pick-and-Place Can
pick_and_place_can_env = suite.make(
    env_name="PickPlaceCan",
    robots="Panda",
    **config,
)

# Nut Assembly Round
nut_assembly_round_env = suite.make(
    env_name="NutAssemblyRound",
    robots="Panda",
    **config,
)

# Table Wiping
nut_assembly_round_env = suite.make(
    env_name="NutAssemblyRound",
    robots="Panda",
    **config,
)

# Door Opening
door_opening_env = suite.make(
    env_name="NutAssemblyRound",
    robots="Panda",
    **config,
)

# Two Arm Lifting
two_arm_lifting_env = suite.make(
    env_name="TwoArmLift",
    robots=["Panda", "Panda"],
    env_configuration="single-arm-opposed",
    **config,
)

# Two Arm Handover
two_arm_handover_env = suite.make(
    env_name="TwoArmHandover",
    robots=["Panda", "Panda"],
    env_configuration="single-arm-opposed",
    **config,
)

# Two Arm Peg-in-Hole
two_arm_peg_in_hole_env = suite.make(
    env_name="TwoArmPegInHole",
    robots=["Panda", "Panda"],
    env_configuration="single-arm-opposed",
    **config,
)

[robosuite WARNING] The config has defined for the controller "left", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for left from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "torso", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for torso from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "head", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for head from self.part_controller_config. (robot.py:151)
[robosuite WARNING] The config has defined for the controller "base", but the robot does not have this component. Skipping, but make sure this is intended.Removing the controller config for base from self.part_controller_config. (robot.py:151)
[robosuite WARNING] Th